var QA = [{"Q":"How do you find P(A union B)? ","A":" P(A) + P(B) - P(A intersect B)"},
{"Q":"What does it mean if A and B are mutually exclusive? ","A":" A intersect B contains no sample points"},
{"Q":"What is the probability that when two coins are flipped the result is heads-heads? ","A":" The answer is 1/4."},
{"Q":"If you roll a pair of dice, what is the probability that you roll a 10 or higher? ","A":" 1 in 6"},
{"Q":"What is an EVENT? ","A":" A specific collection of sample points."},
{"Q":"Define 0! ","A":"1"},
{"Q":"What is the sample space of a 10 sided dice. ","A":" There are 10 possible numbers, therefore a sample space of n = 10."},
{"Q":"How can you find the probability of an event? ","A":" total # of sample points in event / total # of sample points OR sum of all the probabilities of the sample points in event"},
{"Q":"What range must sample point probabilities lie between ","A":" 0-1 (inclusive)"},
{"Q":"When would you use combinations? ","A":" When the order doesn't mattter."},
{"Q":"What is the probability of rolling a 2 when rolling a 6 sided dice? ","A":" 1/6"},
{"Q":"If a z score is less than the mean value, will the z score be positive or negative. ","A":" negative"},
{"Q":"What does the middle line of the box and whisker plot represent? ","A":" It represents the median."},
{"Q":"How do you calculate z-value? ","A":" z= (x - x_bar )/ s"},
{"Q":"What is the symbol for sample mean and what is the symbol for population mean? ","A":" sample mean: x with bar over it population mean: mu"},
{"Q":"What is the interquartile range formula? ","A":" IQR=QU-QL or IQR = Q3-Q1"},
{"Q":"According to the empirical rule, what percent of the data should fall within 2 standard deviations of the mean? ","A":"0.95"},
{"Q":"what are s and s^2? ","A":" standard deviation vs variation"},
{"Q":"What are the distances from the hinges that make up the dimensions of a Box Plot? ","A":" The inner fence is at a distance of 1.5 IQR and the outer fence is at a distance of 3 IQR."},
{"Q":"What does the z score indicate? ","A":" The number of standard deviations away from the mean of a measurement x."},
{"Q":"What do the outer fences on a box plot represent? ","A":" It is the distance of 3IQR from the hinges."},
{"Q":"Is a Pareto chart organized in ascending or descending order? ","A":" Descending."},
{"Q":"What kind of data is a dot plot used for? ","A":" Quantitative data"},
{"Q":"If a sample is left skewed is the median larger or smaller than the mean? ","A":" larger"},
{"Q":"What method can be used to find a middle number of a data set if an outlier skews the mean. ","A":" Take the median"},
{"Q":"What EXCEL formulas are used to find the highest, lowest, and middle values from a set of numerical data? ","A":" '=MAX(), =MIN(), =MEDIAN()"},
{"Q":"What is the formula for class relative frequency? ","A":" class frequency/n"},
{"Q":"If a probability distribution is skewed to the right, what does it say about the mean and median? ","A":" median < mean"},
{"Q":"How do you find the median of an even numbered data set? ","A":" You place the numbers in ascending/descending order then find the mean of the two middle most numbers."},
{"Q":"What are three types of graphs you can use to display qualitative data? ","A":" Pie chart, bar graph, pareto diagram"},
{"Q":"What does standard deviation represent? ","A":" Standard deviation is the root of variance. It measures dispersion/spread of the data by showing the usual distance from the mean amongst observations in a data set."},
{"Q":"What do x̄ and μ mean? ","A":" x̄ = Sample Mean, μ = Population Mean"},
{"Q":"What is the median of the numbers below: 1,2,2,3,3,4,5,5,6 ","A":"3"},
{"Q":"What are the different types of ways to illustrate quantitative data? ","A":" Dot plots, Stem & Leaf, Histograms"}];
